'use strict';
const $=id=>document.getElementById(id), fmt=n=>n.toLocaleString('de-DE',{maximumFractionDigits:1});
const groups={
A:{title:'Was verändert eine Umkehr der Stromrichtung?',short:'Feldrichtung',experiment:'Gerader Leiter · Draufsicht',constant:'Betrag der Stromstärke: 1 A; Abstand des Messpunkts: 2 cm.',steps:['Vergleichen Sie +1 A, 0 A und −1 A. Notieren Sie jeweils den Messwert auf dem Aufgabenblatt.','Beobachten Sie Feldpfeile und Kompass am Messpunkt M. Was ändert sich, was bleibt gleich?','Formulieren Sie eine Aussage zur Stromumkehr. Belegen Sie diese mit dem Vergleich von +1 A und −1 A.'],initial:1,unit:'A',column:'Stromstärke I'},
B:{title:'Wie hängt das Magnetfeld von der Stromstärke ab?',short:'Stromstärke',experiment:'Gerader Leiter · Draufsicht',constant:'Messpunkt: 2 cm vom Leiter; Stromrichtung: aus der Blattebene.',steps:['Stellen Sie nacheinander 0 A, 1 A, 2 A und 4 A ein. Notieren Sie die vier Messwerte auf dem Aufgabenblatt.','Vergleichen Sie 1 A mit 2 A und 2 A mit 4 A. Prüfen Sie dabei auch die Feldrichtung.','Formulieren Sie eine Aussage: Was bewirkt eine Verdopplung der Stromstärke? Nennen Sie ein Wertepaar als Beleg.'],initial:1,unit:'A',column:'Stromstärke I'},
C:{title:'Was bewirken zusätzliche Windungen an einer Spule?',short:'Windungszahl',experiment:'Luftspule · Längsschnitt',constant:'Stromstärke: 1 A; Spulenlänge: 40 cm; Radius: 2 cm; Messpunkt: Spulenmitte.',steps:['Vergleichen Sie 50, 100 und 200 Windungen. Die Spulenlänge bleibt dabei gleich. Notieren Sie die drei Messwerte auf dem Aufgabenblatt.','Vergleichen Sie jeweils eine Verdopplung der Windungszahl. Beobachten Sie Feldstärke und Lage der Pole.','Formulieren Sie eine Aussage: Wie lässt sich das Feld verstärken, ohne die Stromstärke zu erhöhen? Belegen Sie die Aussage mit zwei Messwerten.'],initial:50,unit:'Windungen',column:'Windungszahl N'}
};
let state={A:{value:1},B:{value:1},C:{value:50}},active='A';
function text(x,y,s,extra=''){return `<text x="${x}" y="${y}" ${extra}>${s}</text>`;}
function arrow(x,y,angle,color='#005a9e'){return `<path d="M -17 0 H 14 M 6 -6 L 14 0 L 6 6" transform="translate(${x} ${y}) rotate(${angle})" fill="none" stroke="${color}" stroke-width="2.6"/>`;}
function compass(x,y,angle,on){return `<circle cx="${x}" cy="${y}" r="23" fill="white" stroke="#70869a"/>`+(on?`<g transform="translate(${x} ${y}) rotate(${angle})"><path d="M -17 0 L 0 -5 L 0 5 Z" fill="#8192a5"/><path d="M 17 0 L 0 -5 L 0 5 Z" fill="#bc3737"/></g>`:text(x,y+5,'—','text-anchor="middle"'))+text(x+29,y+5,'M');}
function diagram(g,v){let s='<svg viewBox="0 0 640 320" role="img" aria-labelledby="svgtitle"><title id="svgtitle">'+(g==='C'?'Spulenfeld mit Messpunkt im Zentrum':'Kreisförmiges Leiterfeld mit Messpunkt rechts vom Leiter')+'</title>';
if(g!=='C'){
const on=v!==0,sign=Math.sign(v);if(on){for(const r of [52,90,128]){s+=`<circle cx="255" cy="155" r="${r}" fill="none" stroke="#4385b9" stroke-width="2"/>`;for(const a of [0,120,240]){const rad=a*Math.PI/180;s+=arrow(255+r*Math.cos(rad),155+r*Math.sin(rad),a-sign*90);}}}
s+=`<circle cx="255" cy="155" r="14" fill="white" stroke="#182c43" stroke-width="2"/>`;
if(v>0)s+='<circle cx="255" cy="155" r="4" fill="#182c43"/>';else if(v<0)s+='<path d="M248 148 L262 162 M248 162 L262 148" stroke="#182c43" stroke-width="2"/>';
s+=compass(345,155,v>0?-90:90,on)+text(422,85,v>0?'I aus dem Blatt':v<0?'I in das Blatt':'I = 0 A')+text(422,112,'r = 2 cm')+text(255,307,'Leiterquerschnitt','text-anchor="middle"');
}else{
const n=v/10;for(let i=0;i<n;i++){const x=120+i*400/(n-1);s+=`<path d="M${x} 111 V209" stroke="#ced9e2" stroke-dasharray="4 4"/><circle cx="${x}" cy="111" r="7" fill="white" stroke="#435a6e"/><path d="M${x-3} 108 L${x+3} 114 M${x-3} 114 L${x+3} 108" stroke="#435a6e"/><circle cx="${x}" cy="209" r="7" fill="white" stroke="#435a6e"/><circle cx="${x}" cy="209" r="2" fill="#435a6e"/>`;}
for(const y of [140,180]){s+=`<path d="M110 ${y} H530" stroke="#4385b9" stroke-width="2"/>`+arrow(240,y,180)+arrow(430,y,180);}
s+='<path d="M110 130 C30 35 590 35 530 130 M110 190 C30 285 590 285 530 190" fill="none" stroke="#4385b9" stroke-width="2"/>'+arrow(320,59,0)+arrow(320,261,0)+text(78,166,'N')+text(552,166,'S')+compass(320,160,180,true)+text(320,305,`${v} Windungen · Länge 40 cm`,'text-anchor="middle"');
}return s+'</svg>';}
function update(){const v=state[active].value,m=MagnetModel.measure(active,v);$('diagram').innerHTML=diagram(active,v);$('reading').textContent=fmt(m.field)+' µT';$('direction').textContent=m.direction;$('field-meter').max=active==='C'?650:40;$('field-meter').value=m.field;$('meter-label').textContent=active==='C'?'Feste Skala: 0 bis 650 µT':'Feste Skala: 0 bis 40 µT';const o=$('setting-output');if(o)o.textContent=fmt(v)+' '+groups[active].unit;document.querySelectorAll('[data-current]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.current)===v)));$('legend').textContent=active==='C'?'⊗ oben: Strom ins Blatt · ⊙ unten: aus dem Blatt. Rot: Kompass-Nordende. Gezeichnete Windungen sind stellvertretend.':'Blau: Magnetfeld · Rot: Kompass-Nordende. Die Messposition bleibt unverändert.';}
function select(g){active=g;const c=groups[g];document.querySelectorAll('[data-group]').forEach(b=>{const yes=b.dataset.group===g;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});$('group-label').textContent=`GRUPPE ${g} · ${c.short.toUpperCase()}`;$('question').textContent=c.title;$('experiment-title').textContent=c.experiment;$('constants').textContent=c.constant;$('steps').innerHTML=c.steps.map(t=>'<li>'+t+'</li>').join('');$('controls').innerHTML=g==='A'?'<button data-current="1">+1 A · aus dem Blatt</button><button data-current="0">0 A · aus</button><button data-current="-1">−1 A · ins Blatt</button>':`<label for="setting">${c.column}<input id="setting" type="range" min="${g==='B'?0:50}" max="${g==='B'?4:200}" step="${g==='B'?.5:50}" value="${state[g].value}"><output id="setting-output" for="setting"></output></label>`;
document.querySelectorAll('[data-current]').forEach(b=>b.addEventListener('click',()=>{state[active].value=Number(b.dataset.current);update();}));const setting=$('setting');if(setting)setting.addEventListener('input',()=>{state[active].value=Number(setting.value);update();});update();history.replaceState(null,'','#'+g);}
document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.group)));
$('reset').addEventListener('click',()=>{state[active].value=groups[active].initial;select(active);});
select(groups[location.hash.slice(1)]?location.hash.slice(1):'A');
